# Generated by Django 2.1.5 on 2019-02-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'price_date')},
        ),
    ]
